# Generated by Django 3.0 on 2020-05-26 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_student_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='user_type',
            field=models.CharField(max_length=128),
        ),
    ]
