# Generated by Django 3.0 on 2020-06-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_auto_20200601_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.BooleanField(blank=True, default=False, null=True)),
                ('father', models.CharField(blank=True, max_length=128, null=True)),
                ('mother', models.CharField(blank=True, max_length=128, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=128, null=True)),
                ('street_1', models.CharField(blank=True, max_length=128, null=True)),
                ('street_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('dob', models.CharField(blank=True, max_length=128, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=128, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos', verbose_name='app_files')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_personal_info', to='applicant.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(blank=True, max_length=128, null=True)),
                ('trx_id', models.CharField(blank=True, max_length=128, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment_info', to='applicant.Student')),
            ],
        ),
    ]
