# Generated by Django 3.0 on 2020-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_paymentinfo_personalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
