# Generated by Django 3.0 on 2020-06-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_subject_subjectmaterial_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmaterial',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_files', to='applicant.Subject'),
        ),
    ]
