# Generated by Django 3.0 on 2020-06-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_auto_20200618_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='file',
        ),
        migrations.CreateModel(
            name='MaterialContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='subject', verbose_name='subject_contents')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_materials', to='applicant.SubjectMaterial')),
            ],
        ),
    ]
