# Generated by Django 3.0 on 2020-06-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_auto_20200618_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects_qualified', to='applicant.Student')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='applicant.Subject')),
            ],
        ),
    ]
