# Generated by Django 3.0 on 2021-03-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_edbaseboard_edbaselocation_edbasequalification_edbasesubject_edbaseteacher_edbaseteachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='edbasesubject',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edbaseboardforsubject', to='applicant.EdbaseBoard'),
            preserve_default=False,
        ),
    ]
