# Generated by Django 3.0 on 2021-03-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_edbasesubject_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdbaseStudentSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_student', to='applicant.Student')),
                ('subect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_student_teacher_subject', to='applicant.EdbaseTeacherSubject')),
            ],
        ),
        migrations.CreateModel(
            name='EdbaseStudentQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='applicant.EdbaseQualification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_student_qualification_connection', to='applicant.Student')),
            ],
        ),
        migrations.CreateModel(
            name='EdbaseStudentGuardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian1', models.CharField(blank=True, max_length=128, null=True)),
                ('guardian1relation', models.CharField(blank=True, max_length=128, null=True)),
                ('guardian2', models.CharField(blank=True, max_length=128, null=True)),
                ('guardian2relation', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_student_guardian', to='applicant.Student')),
            ],
        ),
    ]
