# Generated by Django 3.0 on 2021-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0017_edbasestudentguardian_edbasestudentqualification_edbasestudentsubjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='passport',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
