# Generated by Django 3.0 on 2021-03-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0018_personalinfo_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdbaseStudentLocationBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_board', to='applicant.EdbaseBoard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_location', to='applicant.EdbaseLocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_student_loc', to='applicant.Student')),
            ],
        ),
    ]
