# Generated by Django 3.0 on 2021-04-17 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0019_edbasestudentlocationboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdbaseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdbaseSesssion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdbaseStudentBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_batch_student', to='applicant.EdbaseBatch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_student_batch', to='applicant.Student')),
            ],
        ),
        migrations.CreateModel(
            name='EdbaseBatchSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_batch', to='applicant.EdbaseBatch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_subect_batch', to='applicant.EdbaseTeacherSubject')),
            ],
        ),
        migrations.AddField(
            model_name='edbasebatch',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edbase_session_batch', to='applicant.EdbaseSesssion'),
        ),
    ]
