# Generated by Django 3.0 on 2021-04-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0020_auto_20210417_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='edbasebatch',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
