# Generated by Django 3.0 on 2021-04-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0021_edbasebatch_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='edbasestudentbatch',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edbase_subject_batch_student', to='applicant.EdbaseTeacherSubject'),
        ),
    ]
