# Generated by Django 3.0 on 2021-04-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0022_edbasestudentbatch_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edbasestudentbatch',
            name='subject',
        ),
        migrations.AddField(
            model_name='edbasestudentbatch',
            name='edsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edb_stu_sub', to='applicant.EdbaseStudentSubjects'),
        ),
    ]
