# Generated by Django 3.0 on 2021-04-26 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0023_auto_20210418_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdbaseSubjectContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='content', verbose_name='contents')),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_batch', to='applicant.EdbaseBatch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_subject', to='applicant.EdbaseTeacherSubject')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
