# Generated by Django 3.0 on 2021-04-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0024_edbasesubjectcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='edbasestudentbatch',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edb_subject', to='applicant.EdbaseTeacherSubject'),
        ),
    ]
