# Generated by Django 3.0 on 2021-04-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('applicant', '0025_edbasestudentbatch_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdbaseGuardianAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EdbaseGuardianProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_guardian_info', to='applicant.EdbaseStudentGuardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_guardian', to='applicant.Student')),
                ('studentinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_personal_ifo', to='applicant.PersonalInfo')),
                ('useracc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.EdbaseGuardianAccount')),
            ],
        ),
    ]
