# Generated by Django 3.0 on 2021-05-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0027_edbaseroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='edbaseroutine',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.EdbaseQualification'),
        ),
    ]
